### ISSUE TITLE
Zol issues with managing running of HMM to find gene-cluster homolog segments

### ISSUE THREAD

**Issue by lucssantos** [Kalan-Lab/zol#5]
I have been trying to run Zol through the prepTG/fai/zol pipeline, but I am always facing the same issue after Step 4 (Identifying homologous gene-cluster segments) starts. The run always generates the error below (independently if I am trying to use any of the 3 input types):

```
→ fai -pq cluster_ptn.faa -tg prepTG_DB -o fai_Results/ -c 3 -gp
Output directory exists. Overwriting in 5 seconds ...
 Running fai version '1.02'
Beginning fai searches using protein queries FASTA file at: cluster_ptn.faa
--------------------
Step 1
--------------------
Getting protein sequences of known gene-cluster instance(s).
--------------------
Step 2
--------------------
Running DIAMOND BLASTp and Processing Results.
--------------------
Step 3
--------------------
Loading target genomes database prepared by prepTG.
--------------------
Step 4
--------------------
Identifying homologous gene-cluster segments.
Issues with managing running of HMM to find gene-cluster homolog segments.
'NoneType' object is not subscriptable
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Volumes/Expansion/fai/zol/zol/fai.py", line 649, in identify_gc_instances
    for scaffold in hgs_ordered_dict[sample]:
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/Expansion/fai/zol/zol/fai.py", line 631, in identifyGCInstances
    p.map(identify_gc_instances, identify_gc_segments_input)
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Expansion/fai/zol/zol_conda_env/bin/fai", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Volumes/Expansion/fai/zol/bin/fai", line 527, in <module>
    faiMain()
  File "/Volumes/Expansion/fai/zol/bin/fai", line 494, in faiMain
    fai.identifyGCInstances(query_information, target_information, diamond_results, hmm_work_dir, logObject,
  File "/Volumes/Expansion/fai/zol/zol/fai.py", line 641, in identifyGCInstances
    raise RuntimeError(traceback.format_exc())
RuntimeError: multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Volumes/Expansion/fai/zol/zol/fai.py", line 649, in identify_gc_instances
    for scaffold in hgs_ordered_dict[sample]:
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/Expansion/fai/zol/zol/fai.py", line 631, in identifyGCInstances
    p.map(identify_gc_instances, identify_gc_segments_input)
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Volumes/Expansion/fai/zol/zol_conda_env/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
```

Any ideas of what might be happening?

**Comment by raufs** [comment]
Hi @lucssantos ,

Thanks for giving zol a try! 

Yes, this was confusing me as well but if you please check out zol from Github again since v1.2.1, this issue should be resolved. This is related to a difference in the multiprocessing library between macOS (where I assume you are running it) and unix. 

Also, I've been making some changes to the code base recently to develop a docker image and bioconda recipe, these should not affect installation the way it is described and none of the programs should be changing. 

Please let me know if your issue persists or a new one comes up!
Rauf
